spring:
  datasource:
    url: jdbc:h2:mem:bankdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  application:
    name: spending-insight-agent

openai:
  api:
    key: ${openai_key}

logging:
  level:
    root: INFO
    dev.langchain4j: DEBUG
    dev.langchain4j.agent: DEBUG
    dev.langchain4j.agent.tool: DEBUG
    dev.langchain4j.model: DEBUG
    dev.langchain4j.memory: DEBUG
    dev.langchain4j.service: DEBUG
    dev.langchain4j.data: DEBUG
    com.hbs.spending_insight_agent: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
